module.exports = [
    { name: "meme", description: "Get a random meme", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "😂 Random Meme!" }, { quoted: m }); } },
    { name: "joke", description: "Get a random joke", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🤣 Random Joke!" }, { quoted: m }); } },
    { name: "roast", description: "Roast someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🔥 Roasted!" }, { quoted: m }); } },
    { name: "compliment", description: "Compliment someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💝 You're awesome!" }, { quoted: m }); } },
    { name: "ship", description: "Ship two people", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💑 100% Match!" }, { quoted: m }); } },
    { name: "8ball", description: "Ask magic 8ball", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🎱 Yes!" }, { quoted: m }); } },
    { name: "truth", description: "Truth challenge", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🤔 Truth: ..." }, { quoted: m }); } },
    { name: "dare", description: "Dare challenge", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "😈 Dare: ..." }, { quoted: m }); } },
    { name: "wyr", description: "Would you rather", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🤷 Would you rather..." }, { quoted: m }); } },
    { name: "pickup", description: "Pickup line", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "😏 Pickup line..." }, { quoted: m }); } },
    { name: "trivia", description: "Trivia question", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🧠 Trivia..." }, { quoted: m }); } },
    { name: "riddle", description: "Riddle", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🤔 Riddle..." }, { quoted: m }); } },
    { name: "advice", description: "Get advice", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💡 Advice..." }, { quoted: m }); } },
    { name: "hack", description: "Fake hack someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💻 Hacking..." }, { quoted: m }); } },
    { name: "kill", description: "Fake kill someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💀 Killed!" }, { quoted: m }); } },
    { name: "love", description: "Love percentage", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "❤️ 99% Love!" }, { quoted: m }); } },
    { name: "gay", description: "Gay percentage", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🌈 100% Gay!" }, { quoted: m }); } },
    { name: "iq", description: "IQ test", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🧠 IQ: 150" }, { quoted: m }); } },
    { name: "dare2", description: "Another dare", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "😈 Dare!" }, { quoted: m }); } },
    { name: "truth2", description: "Another truth", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🤔 Truth!" }, { quoted: m }); } },
    { name: "slap", description: "Slap someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "👋 Slapped!" }, { quoted: m }); } },
    { name: "pat", description: "Pat someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🤗 Patted!" }, { quoted: m }); } },
    { name: "hug", description: "Hug someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🫂 Hugged!" }, { quoted: m }); } },
    { name: "kiss", description: "Kiss someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💋 Kissed!" }, { quoted: m }); } },
    { name: "punch", description: "Punch someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "👊 Punched!" }, { quoted: m }); } },
    { name: "kick2", description: "Kick someone (fun)", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🦶 Kicked!" }, { quoted: m }); } },
    { name: "bite", description: "Bite someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🦷 Bitten!" }, { quoted: m }); } },
    { name: "lick", description: "Lick someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "👅 Licked!" }, { quoted: m }); } },
    { name: "poke", description: "Poke someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "👉 Poked!" }, { quoted: m }); } },
    { name: "tickle", description: "Tickle someone", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🤣 Tickled!" }, { quoted: m }); } },
    { name: "dance", description: "Dance", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💃 Dancing!" }, { quoted: m }); } },
    { name: "sing", description: "Sing", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🎤 Singing!" }, { quoted: m }); } },
    { name: "cry", description: "Cry", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "😭 Crying!" }, { quoted: m }); } },
    { name: "laugh", description: "Laugh", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "😂 Laughing!" }, { quoted: m }); } },
    { name: "sleep", description: "Sleep", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "😴 Sleeping!" }, { quoted: m }); } },
    { name: "eat", description: "Eat", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "😋 Eating!" }, { quoted: m }); } },
    { name: "run", description: "Run", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🏃 Running!" }, { quoted: m }); } },
    { name: "jump", description: "Jump", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🦘 Jumping!" }, { quoted: m }); } },
    { name: "fly", description: "Fly", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🕊️ Flying!" }, { quoted: m }); } },
    { name: "swim", description: "Swim", category: "fun", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🏊 Swimming!" }, { quoted: m }); } }
];
