const blue = { bot: [] };

blue.bot.push(
    { name: "afk", description: "Set AFK", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "✅ You are now AFK" }, { quoted: m }); } },
    { name: "rank", description: "Check rank", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📊 Your rank: 1" }, { quoted: m }); } },
    { name: "info", description: "Bot info", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🤖 BLUEBOT-XMD Info" }, { quoted: m }); } },
    { name: "alive", description: "Check if alive", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "✨ I am alive!" }, { quoted: m }); } },
    { name: "echo", description: "Echo message", category: "general", async execute(sock, m, { from, text }) { await sock.sendMessage(from, { text: text || "Echo!" }); } },
    { name: "profile", description: "Check profile", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "👤 Your Profile" }, { quoted: m }); } },
    { name: "quote", description: "Get quote", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💭 Random Quote" }, { quoted: m }); } },
    { name: "fact", description: "Get fact", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🤓 Random Fact" }, { quoted: m }); } },
    { name: "weather", description: "Check weather", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "☀️ Weather info..." }, { quoted: m }); } },
    { name: "translate", description: "Translate text", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🌐 Translation..." }, { quoted: m }); } },
    { name: "shorturl", description: "Shorten URL", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🔗 Short URL..." }, { quoted: m }); } },
    { name: "qr", description: "Generate QR", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📱 QR Code..." }, { quoted: m }); } },
    { name: "google", description: "Google search", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🔍 Google Search..." }, { quoted: m }); } },
    { name: "wiki", description: "Wikipedia search", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📚 Wikipedia..." }, { quoted: m }); } },
    { name: "github", description: "GitHub search", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💻 GitHub Search..." }, { quoted: m }); } },
    { name: "npm", description: "NPM search", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📦 NPM Search..." }, { quoted: m }); } },
    { name: "calculator", description: "Calculate", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🧮 Result..." }, { quoted: m }); } },
    { name: "time", description: "Check time", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "⏰ Current Time..." }, { quoted: m }); } },
    { name: "date", description: "Check date", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📅 Current Date..." }, { quoted: m }); } },
    { name: "speed", description: "Check speed", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "⚡ Speed test..." }, { quoted: m }); } },
    { name: "owner2", description: "Owner info", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "👑 Owner Info" }, { quoted: m }); } },
    { name: "script2", description: "Script info", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📜 Script Info" }, { quoted: m }); } },
    { name: "repo", description: "Repo link", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💻 Repo Link" }, { quoted: m }); } },
    { name: "cpu", description: "CPU info", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💻 CPU Info" }, { quoted: m }); } },
    { name: "ram", description: "RAM info", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💾 RAM Info" }, { quoted: m }); } },
    { name: "os", description: "OS info", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💻 OS Info" }, { quoted: m }); } },
    { name: "node", description: "Node info", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🟢 Node.js Info" }, { quoted: m }); } },
    { name: "ping2", description: "Ping test", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🏓 Pong!" }, { quoted: m }); } },
    { name: "uptime2", description: "Uptime test", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "⏱️ Uptime..." }, { quoted: m }); } },
    { name: "runtime2", description: "Runtime test", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "⏱️ Runtime..." }, { quoted: m }); } },
    { name: "status", description: "Bot status", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📊 Bot Status" }, { quoted: m }); } },
    { name: "news", description: "Get news", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📰 Latest News" }, { quoted: m }); } },
    { name: "crypto", description: "Crypto prices", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💰 Crypto Prices" }, { quoted: m }); } },
    { name: "stock", description: "Stock prices", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📈 Stock Prices" }, { quoted: m }); } },
    { name: "currency", description: "Currency rates", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "💱 Currency Rates" }, { quoted: m }); } },
    { name: "define", description: "Define word", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📖 Definition..." }, { quoted: m }); } },
    { name: "urban", description: "Urban dictionary", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "📖 Urban Dictionary..." }, { quoted: m }); } },
    { name: "lyrics", description: "Get lyrics", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🎵 Lyrics..." }, { quoted: m }); } },
    { name: "imdb", description: "Movie info", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "🎬 Movie Info..." }, { quoted: m }); } },
    { name: "anime", description: "Anime info", category: "general", async execute(sock, m, { from }) { await sock.sendMessage(from, { text: "⛩️ Anime Info..." }, { quoted: m }); } }
);

module.exports = blue.bot;
